Selective replacement of images
IBM/cloud-pak-operations-cli pull request #110
Opened 2022-03-14 15:14 UTC by johker01

This pull request allows replacing specific images in the Data Gate pod for testing purposes, e.g. when wanting to run Data Gate test cases in a CI/CD pipeline. It is possible to either supply a deployment name or if not supplied, the CLI command will try to automatically derive the deployment name. This will not work, if more than one deployment is running on the same cluster.
This is a synchronous call, meaning that the command will only return when the image replacement is done and all containers in the pod are running. The mechanism how to check whether the pod has been restarted can and will be improved in a future pull request, as it is done [here](https://github.com/IBM/cloud-pak-operations-cli/blob/master/cpo/lib/cloud_pak_for_data/cpd_4_0_0/cpd_manager.py#L1366).

2022-03-15 07:18 UTC, jensmueller-com requested changes

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/lib/openshift/oc.py
> +    oc_get_pods_args = ["get", "pods"]
Either return and parse JSON (`oc get pods --output json`) or use JSONPath (`oc get pods {pod_name} --output jsonpath="{.status.phase}"`)

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/lib/openshift/oc.py
> +    oc_get_custom_resource_args = ["get", custom_resource_kind, custom_resource_id, "-o", "json"]
Use long command line options (see [coding guidelines](https://github.com/IBM/cloud-pak-operations-cli/blob/master/docs/coding_guidelines.md#command-line-options))

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/lib/openshift/oc.py
> +    """Get the custom resource for a given kind and id"""
"id" → "ID"

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/lib/openshift/types/get_pod_entry.py
> +#  Copyright 2022 IBM Corporation
Remove and either return and parse JSON (`oc get pods --output json`) or use JSONPath (`oc get pods {pod_name} --output jsonpath="{.status.phase}"`) [see `cpo/lib/openshift/oc.py`]

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/commands/cluster/replace_data_gate_images.py
> +def _is_pod_running_from_deployment(deployment_name: str):
Add return type

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/commands/cluster/replace_data_gate_images.py
> +def _is_pod_not_running_from_deployment(deployment_name: str):
Add return type

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/commands/cluster/replace_data_gate_images.py
> +def replace_data_gate_images(
"data_gate_images" → "db2_data_gate_images"

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/commands/cluster/replace_data_gate_images.py
> +def _get_data_gate_pod_name_from_deployment_name(deployment_name: str) -> str:
"_get_data_gate_pod_name_from_deployment_name" → "_get_db2_data_gate_pod_name_from_deployment_name"

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/commands/cluster/replace_data_gate_images.py
> +def _replace_image_in_data_gate_instance_service_custom_resource(
"_replace_image_in_data_gate_instance_service_custom_resource" → "_replace_image_in_db2_data_gate_instance_service_custom_resource"

2022-03-15 07:18 UTC, jensmueller-com commented on cpo/commands/cluster/replace_data_gate_images.py
> +    """Replace a single or multiple specific component(s) of a given deployment.
"given deployment" → "given Db2 Data Gate deployment"

2022-03-15 14:44 UTC, johker01 commented on cpo/commands/cluster/replace_data_gate_images.py
> +#  Copyright 2021 IBM Corporation
done

2022-03-15 15:05 UTC, johker01 commented on cpo/commands/cluster/replace_data_gate_images.py
> +    custom_resource_json = oc.get_custom_resource("datagateinstanceservice", dg_id)
understood

2022-04-04 02:50 UTC, jensmueller-com approved these changes

2022-04-04 09:28 UTC, merged